name: Docker Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 8000:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t employee_project .
      
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 employee_project
      
      - name: Test the running Docker container
        run: |
          curl http://localhost:8000
